apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookswap
    microservice: db
  name: db
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: bookswap
      microservice: db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bookswap
        microservice: db
    spec:
      containers:
        - image: pedroavpereiradev/book-swap-db:latest
          imagePullPolicy: IfNotPresent
          name: db
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: db-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: db-configmap
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookswap
    microservice: db
  name: db
  namespace: default
spec:
  selector:
    app: bookswap
    microservice: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432
